import type { ApplyFieldConfig } from "../types/apply";

export const COMMON_FIELDS: ApplyFieldConfig[] = [
  {
    key: "name",
    label: "Name",
    type: "text",
    required: true,
    placeholder: "Your name",
    width: "half",
  },
  {
    key: "discord",
    label: "Discord Username",
    type: "text",
    required: true,
    placeholder: "e.g. Name#1234",
    width: "half",
  },
  {
    key: "timezone",
    label: "Timezone",
    type: "text",
    placeholder: "e.g. CET / GMT+1",
    width: "half",
  },
  {
    key: "age",
    label: "Age",
    type: "text",
    placeholder: "Your age",
    width: "half",
  },
  {
    key: "portfolioUrl",
    label: "Portfolio URL",
    type: "url",
    placeholder: "https://your-portfolio.com",
    width: "half",
  },
  {
    key: "availability",
    label: "Availability",
    type: "text",
    placeholder: "e.g. 4 evenings a week",
    width: "half",
  },
  {
    key: "extraLinks",
    label: "Extra Links",
    type: "textarea",
    placeholder: "Add YouTube links, references, Discord links, etc.",
    minHeight: 120,
    width: "full",
  },
  {
    key: "experience",
    label: "Experience",
    type: "textarea",
    required: true,
    placeholder: "Tell us about your experience",
    minHeight: 120,
    width: "full",
  },
  {
    key: "motivation",
    label: "Motivation",
    type: "textarea",
    required: true,
    placeholder: "Why should we accept you?",
    minHeight: 150,
    width: "full",
  },
];

export const ROLE_FIELDS: Record<string, ApplyFieldConfig[]> = {
  Developer: [
    {
      key: "developerSkills",
      label: "Developer Skills",
      type: "textarea",
      required: true,
      placeholder: "Which languages, frameworks, tools or systems do you know?",
      width: "full",
    },
    {
      key: "developerProjects",
      label: "Developer Projects",
      type: "textarea",
      required: true,
      placeholder: "Tell us about projects you worked on.",
      width: "full",
    },
  ],
  Supporter: [
    {
      key: "supportCases",
      label: "Support Experience",
      type: "textarea",
      required: true,
      placeholder: "Tell us about moderation, support, or user issues.",
      width: "full",
    },
    {
      key: "supportCommunication",
      label: "Communication Skills",
      type: "textarea",
      required: true,
      placeholder: "How do you deal with difficult users or conflict situations?",
      width: "full",
    },
  ],
  "Competitive Manager": [
    {
      key: "competitiveKnowledge",
      label: "Competitive Knowledge",
      type: "textarea",
      required: true,
      placeholder: "Describe your knowledge of competitive systems, teams, or tournaments.",
      width: "full",
    },
    {
      key: "competitivePlans",
      label: "Plans for Competitive",
      type: "textarea",
      required: true,
      placeholder: "What would you improve or build in the competitive area?",
      width: "full",
    },
  ],
  Manager: [
    {
      key: "managerLeadership",
      label: "Leadership Experience",
      type: "textarea",
      required: true,
      placeholder: "Tell us about leadership, team handling, or project management.",
      width: "full",
    },
    {
      key: "managerOrganization",
      label: "Organization Skills",
      type: "textarea",
      required: true,
      placeholder: "How do you organize people, tasks, and priorities?",
      width: "full",
    },
  ],
  Director: [
    {
      key: "directorVision",
      label: "Vision",
      type: "textarea",
      required: true,
      placeholder: "What long-term vision would you bring to Auros?",
      width: "full",
    },
    {
      key: "directorResponsibility",
      label: "Responsibility",
      type: "textarea",
      required: true,
      placeholder: "Why are you ready for a high-responsibility leadership role?",
      width: "full",
    },
  ],
  Other: [
    {
      key: "otherStrengths",
      label: "Why do you fit this role?",
      type: "textarea",
      required: true,
      placeholder: "Tell us what makes you a good fit for this position.",
      width: "full",
    },
  ],
};